@bg school
@sprite kuro
@bgm 70_Love

@qm
@qmBtn "Guardar" event Save()
@qmEnd

K: Hello, welcome to this engine test!
K: my name is {K} and I am here for the sole purpose of debugging this project....
K: everything seems to be working properly...

@choice
  @option "I found a bug!" event Set(chek, true)
  @option "No bugs" event Set(chek, false)
@end_choice

@if chek
  @bgm escape-ofv
  K: Oh, you found a bug! Thank you very much for finding it!
  K: Be sure to report it on github!
@else
  @bgm escape-ofv
  K: Perfect! everything works correctly
@endif

@end

 